// src/components/SearchBar.svelte
<script lang="ts">
    export let onSearch: (query: string) => void;

    const handleInput = (event: Event) => {
        const target = event.target as HTMLInputElement;

        onSearch(target.value);
    };
</script>

<div class="searchbar">
    <input type="text" placeholder="Search" on:input={handleInput} />
</div>

<style lang="scss">
    .searchbar {
        width: 100%;
        height: 100%;

        user-select: none;

        input {
            width: 100%;
            height: 100%;

            border: none;
            text-align: center;
            background-color: transparent;
            color: #ffffff;
            outline: none;
        }
    }
</style>

// app/src/components/SearchBar.tsx
import { FunctionalComponent } from "preact";
import "./SearchBar.scss";

interface SearchBarProps {
    // eslint-disable-next-line no-unused-vars
    onSearch: (query: string) => void;
}

export const SearchBar: FunctionalComponent<SearchBarProps> = ({
    onSearch,
}) => {
    const handleInput = (event: Event) => {
        const target = event.target as HTMLInputElement;
        onSearch(target.value);
    };

    return (
        <div className="searchbar">
            <input type="text" placeholder="Search" onInput={handleInput} />
        </div>
    );
};
